//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esecui.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MRU {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MRU"]));
            }
            set {
                this["MRU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color BestFitnessLineColor {
            get {
                return ((global::System.Drawing.Color)(this["BestFitnessLineColor"]));
            }
            set {
                this["BestFitnessLineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color CurrentBestLineColor {
            get {
                return ((global::System.Drawing.Color)(this["CurrentBestLineColor"]));
            }
            set {
                this["CurrentBestLineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color CurrentMeanLineColor {
            get {
                return ((global::System.Drawing.Color)(this["CurrentMeanLineColor"]));
            }
            set {
                this["CurrentMeanLineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color CurrentWorstLineColor {
            get {
                return ((global::System.Drawing.Color)(this["CurrentWorstLineColor"]));
            }
            set {
                this["CurrentWorstLineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double BestFitnessLineThickness {
            get {
                return ((double)(this["BestFitnessLineThickness"]));
            }
            set {
                this["BestFitnessLineThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double CurrentBestLineThickness {
            get {
                return ((double)(this["CurrentBestLineThickness"]));
            }
            set {
                this["CurrentBestLineThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double CurrentMeanLineThickness {
            get {
                return ((double)(this["CurrentMeanLineThickness"]));
            }
            set {
                this["CurrentMeanLineThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double CurrentWorstLineThickness {
            get {
                return ((double)(this["CurrentWorstLineThickness"]));
            }
            set {
                this["CurrentWorstLineThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color BestFitnessLineColorProjector {
            get {
                return ((global::System.Drawing.Color)(this["BestFitnessLineColorProjector"]));
            }
            set {
                this["BestFitnessLineColorProjector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color CurrentBestLineColorProjector {
            get {
                return ((global::System.Drawing.Color)(this["CurrentBestLineColorProjector"]));
            }
            set {
                this["CurrentBestLineColorProjector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color CurrentMeanLineColorProjector {
            get {
                return ((global::System.Drawing.Color)(this["CurrentMeanLineColorProjector"]));
            }
            set {
                this["CurrentMeanLineColorProjector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color CurrentWorstLineColorProjector {
            get {
                return ((global::System.Drawing.Color)(this["CurrentWorstLineColorProjector"]));
            }
            set {
                this["CurrentWorstLineColorProjector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double BestFitnessLineThicknessProjector {
            get {
                return ((double)(this["BestFitnessLineThicknessProjector"]));
            }
            set {
                this["BestFitnessLineThicknessProjector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double CurrentBestLineThicknessProjector {
            get {
                return ((double)(this["CurrentBestLineThicknessProjector"]));
            }
            set {
                this["CurrentBestLineThicknessProjector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double CurrentMeanLineThicknessProjector {
            get {
                return ((double)(this["CurrentMeanLineThicknessProjector"]));
            }
            set {
                this["CurrentMeanLineThicknessProjector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double CurrentWorstLineThicknessProjector {
            get {
                return ((double)(this["CurrentWorstLineThicknessProjector"]));
            }
            set {
                this["CurrentWorstLineThicknessProjector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double AxisThickness {
            get {
                return ((double)(this["AxisThickness"]));
            }
            set {
                this["AxisThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double AxisThicknessProjector {
            get {
                return ((double)(this["AxisThicknessProjector"]));
            }
            set {
                this["AxisThicknessProjector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Circle")]
        public global::VisualiserLib.VisualiserPointShape VisualiserShape {
            get {
                return ((global::VisualiserLib.VisualiserPointShape)(this["VisualiserShape"]));
            }
            set {
                this["VisualiserShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Circle")]
        public global::VisualiserLib.VisualiserPointShape VisualiserShapeProjector {
            get {
                return ((global::VisualiserLib.VisualiserPointShape)(this["VisualiserShapeProjector"]));
            }
            set {
                this["VisualiserShapeProjector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBlue")]
        public global::System.Drawing.Color VisualiserBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["VisualiserBorderColor"]));
            }
            set {
                this["VisualiserBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double VisualiserBorderThickness {
            get {
                return ((double)(this["VisualiserBorderThickness"]));
            }
            set {
                this["VisualiserBorderThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 0, 0, 255")]
        public global::System.Drawing.Color VisualiserFillColor {
            get {
                return ((global::System.Drawing.Color)(this["VisualiserFillColor"]));
            }
            set {
                this["VisualiserFillColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double VisualiserSize {
            get {
                return ((double)(this["VisualiserSize"]));
            }
            set {
                this["VisualiserSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBlue")]
        public global::System.Drawing.Color VisualiserBorderColorProjector {
            get {
                return ((global::System.Drawing.Color)(this["VisualiserBorderColorProjector"]));
            }
            set {
                this["VisualiserBorderColorProjector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double VisualiserBorderThicknessProjector {
            get {
                return ((double)(this["VisualiserBorderThicknessProjector"]));
            }
            set {
                this["VisualiserBorderThicknessProjector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32, 0, 0, 255")]
        public global::System.Drawing.Color VisualiserFillColorProjector {
            get {
                return ((global::System.Drawing.Color)(this["VisualiserFillColorProjector"]));
            }
            set {
                this["VisualiserFillColorProjector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public double VisualiserSizeProjector {
            get {
                return ((double)(this["VisualiserSizeProjector"]));
            }
            set {
                this["VisualiserSizeProjector"] = value;
            }
        }
    }
}
